Dashboard
Trainy-ai/konduktor pull request #68
Opened 2024-10-22 03:15 UTC by ryanhayame

Created localhost dashboard to manage skypilot/kubernetes/kueue workloads.

Features include:
1. Grafana konduktor dashboard embedding
2. Loki live logs (search + filtering by namespace)
3. Kueue UI to view, delete, and modify priority of workloads

Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)

**0 testing, good luck :) (you should review kube-prometheus-stack.values changes closely)**

2024-10-23 23:48 UTC, asaiacai reviewed
looks good. left some comments mostly around moving stuff around.

2024-10-24 00:26 UTC, ryanhayame commented on konduktor/dashboard/frontend/README.md
> +This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).
deleted this file; the real README is in /dashboard

2024-10-24 00:28 UTC, ryanhayame commented on konduktor/dashboard/backend/requirements.txt
> +Flask
should I use your pyproject.toml in the root directory, or make a new pyproject.toml in /dashboard

2024-10-24 03:51 UTC, ryanhayame commented on konduktor/dashboard/backend/requirements.txt
> +Flask
Do i put it under tool.poetry.group.dev.dependencies], [tool.poetry.dependencies], or do i make a new one? If I have to make a new one, what should I call it?

2024-10-24 03:54 UTC, ryanhayame commented on konduktor/dashboard/backend/requirements.txt
> +Flask
Also, the requirements.txt is mainly for the Docker to know how to run just the backend container (only code inside /backend), separate from everything else. Does this change anything? Should I still do this?

2024-10-24 20:55 UTC, asaiacai commented on konduktor/dashboard/backend/requirements.txt
> +Flask
> Do i put it under [tool.poetry.group.dev.dependencies], [tool.poetry.dependencies], or do i make a new one? If I have to make a new one, what should I call it?

yes create a new one using `poetry add --group dashboard`

2024-11-05 22:13 UTC, asaiacai requested changes
looks good. i'll probably have you walk through it with me before merging but this lgtm

2024-11-05 22:13 UTC, asaiacai commented on konduktor/dashboard/backend/sockets.py
> +PROD_LOGS_URL = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/query_range"
we should just have this toggleable via an environment variable, i.e.
```
os.environ.get("LOGS_URL", "http://loki.loki.svc.cluster.local:3100/loki/api/v1/query_range)
```

2024-11-05 22:13 UTC, asaiacai commented on konduktor/dashboard/backend/main.py
> +        """
for debugging lines like these it would be better if we put these statements in `logger.debug` instead of just commented out `print` statements that can be toggled via environment variable like `KONDUKTOR_DEBUG=1`

2024-11-05 22:13 UTC, asaiacai commented on konduktor/dashboard/backend/main.py
> +"""
Same here, better to move this debugging functions out of this file into something like `utils.py` and with `logger.debug`

2024-11-05 22:13 UTC, asaiacai commented on konduktor/dashboard/backend/sockets.py
> +    # print(f'SELECTED NAMESPACES (GET_LOGS): {SELECTED_NAMESPACES}')
`logger.debug` here as well

2024-11-05 22:13 UTC, asaiacai commented on konduktor/dashboard/backend/sockets.py
> +    print("Client disconnected")
`logger.debug`

2024-11-07 20:13 UTC, asaiacai requested changes
looks good, please consolidate the logging logic to `konduktor/logging.py`

2024-11-07 20:13 UTC, asaiacai commented on konduktor/dashboard/backend/main.py
> +logger = logging.getLogger(__name__)
please use this instead
```
logger = konduktor_logging.get_logger(__name__)
```
see `konduktor/controller/parse.py`

2024-11-07 20:13 UTC, asaiacai commented on konduktor/dashboard/backend/main.py
> +logging.basicConfig(
setting the logging verbosity should be done in `konduktor/logging.py` please move that logic there and test it

2024-11-08 16:54 UTC, ryanhayame commented
nvm found bug; still fixing

2024-11-11 22:24 UTC, asaiacai approved these changes
this lgtm. awesome work @ryanhayame

2024-11-11 22:25 UTC, merged